##Key files to Run Cloud Build
##Automating cloud build process ---> creating Trigger in cloud build
##clone repository --> Cloning -->GCR i/o Cloud Build to connect Git command
##Build Docker image --> it will build & automate docker's
##Push Docker image to google container registery
##It will Create Cloud Run service with Docker image

steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/VinodUshake/ment360demo.git"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/first-melody-361000/dynamicment360:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/first-melody-361000/dynamicment360:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "ment360cloudbuild", "--image", "gcr.io/first-melody-361000/dynamicment360:latest", "--allow-unauthenticated", "--region", "us-central1"]
images:
- gcr.io/first-melody-361000/dynamicment360:latest